config:
  ssh:
    fg: white
    bg: red
  path:
    fg: white
    bg: blue
profiles:
  - segments:
      - type: ssh
        size: long
      - type: userhost
        size: long
      - type: path
        size: long
      - type: git
        size: long
      - type: kube
        size: long
      - type: time
        size: long
        location: right
  - segments:
      - type: ssh
        size: long
      - type: userhost
        size: long
      - type: path
        size: long
      - type: git
        size: long
      - type: kube
        size: long
        location: right
